package wasmcloud:mcp;

world mcp {
   export mcp-handler;
}

interface mcp-handler {
    use wasi:http/types@0.2.2.{incoming-request, response-outparam};
    
    mcp-handle: func(request: incoming-request, response: response-outparam);
}
